#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: sk-2c190100645d4ad3b2c635f7a81854ac
#      model-name: deepseek-chat
#      log-requests: true
#      log-responses: true
#      timeout: 60

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/text_to_sql?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&remarks=true&useInformationSchema=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰 (session_id -> sessionId)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 在控制台打印 SQL 语句，方便调试

